apiVersion: v1
kind: ConfigMap
metadata:
  name: drug-sales-config
  namespace: drug-sales
data:
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  API_GATEWAY_URL: "http://api-gateway:5000"
  POSTGRES_DB: "drug_prediction"
  POSTGRES_USER: "prediction_user"
  REDIS_URL: "redis://redis:6379/0"
