apiVersion: v1
kind: Service
metadata:
  name: advanced-ai-service
  namespace: drug-sales
spec:
  type: ClusterIP
  selector:
    app: advanced-ai-service
  ports:
    - name: http
      port: 5003
      targetPort: 5003
