apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: drug-sales
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: frontend-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
